lists:
  test1:
    interval: 20
    minimumPlayers: 0
    permission: none
    type: default
    commands:
    - '[AutoCommandsPlus] Hi everyone!'
    - '@>/title %player% subtitle It'' a subtitle! Woohoo!>;@>/title %player% title Welcome to our server!'
    # notice, second time you don't need to use $ (%randomplayer% is permanent variable)
    - '$!>/eco give %randomplayer% 1000;>!>%randomplayer%, you won a lottery!>;@>%randomplayer% won a lottery!'
    - '$>Have a nice day, %randomplayer% (everyone will see that)'
    - '!>Only latest randomplayer will see that. Hi, %randomplayer%'
  test2:
    interval: 5
    minimumPlayers: 2
    permission: receive.messages
    type: random
    commands:
    - '1, %player%'
    - '2, %online%'
    - '3, %balance%'
    - '$!>4, %randomplayer%'
  # will be available soon
  _first:
    # 300 seconds = 5 minutes
    interval: 300
    # only default is supported now
    type: default
    # if bigger than 0, commands will be ran only if there are minimum players on the server
    minimumPlayers: 0
    # player needs this permission to run the commands (starting with '@') with the player
    permission: none
    commands:
     # if you want to just send message to all players, put it as a command (without / or something)
     # you can run multiple commands using >;
     # you can delay commands by using >;%2s;> where %2s means 2 seconds
     # in this example first command ran, then wait for 2 seconds and then run second command
     # '@' runs command to every player (you can use %player% placeholder)
     # '&' reselects random player (placeholder is %randomplayer%)
     # '!' runs command or shows the message only to random player
     # you can also use %randomplayer% after the command with $-prefix (every command with $-prefix will reselect random player)
     # '#' runs command as player (use with '@' or '!')
     # '-' excludes random player from '@'
     - '@>/tell %player% Hi!;2s>;@>/tell %player% 2 seconds passed'
     - '/tm msg Donate to us! /donate'
     - '$#>/pay admin 1000>;$/tell %randplayer% You won the lottery!>;-@>/tell %player% %randplayer% won the lottery!'
     - '$>/tell %randplayer% Wow! You are the first!>;$>/tell %randplayer% Wow! You are the second!'
  _second:
    interval: 60
    permission: autocommands.admin
    minimumPlayers: 0
    type: random
    commands:
    - '@>/tell %player% Hello, admin!'
locale:
  noPermission: 'You don''t have enough permissions for this!'
  wrongTellp: 'Usage: /tellp <player> <message>'
  pluginReloaded: 'Plugin has been successfully reloaded!'
debug: false