name: AutoCommandsPlus
main: acse.AutoCommands.AutoCommands
author: MikroAcse
softdepend: [Vault]
version: 1.1.9
commands:
    autocommands:
        aliases: [ac, autocommandsplus, acp]
    tellp:
        aliases: [raw]