name: AutoCommandsPlus
main: acse.AutoCommands.AutoCommands
author: MikroAcse
softdepend: [Vault, PlaceholderAPI]
version: 1.2.0
commands:
    autocommands:
        aliases: [autocommandsplus, acp]
    tellp:
        aliases: [raw]